FROM quay.io/jupyterhub/jupyterhub:5.4.3

RUN pip install --no-cache-dir \
    jupyter_server \
    jupyterlab \
    jupyterhub-ldapauthenticator \
    dockerspawner \
    numpy \
    pandas \
    matplotlib
