#!/usr/bin/env python3
"""
Recreate P88-Tier-8.ipynb with fixed JSON structure
"""

import json

# Create the notebook structure with proper JSON formatting
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 88. The Supplier Selection & Order Allocation Problem\n",
                "## Tier 8: Value-Aligned & Ethical Framework\n",
                "\n",
                "### Key assumptions\n",
                "- Ethical constraints are integrated into supplier selection decisions\n",
                "- Multiple stakeholder groups have different values and priorities\n",
                "- Constitutional AI principles guide automated decision making\n",
                "- Bias detection and mitigation systems are in place\n",
                "- Continuous compliance monitoring ensures ethical standards\n",
                "\n",
                "### Approach (step-by-step)\n",
                "1. **Constitutional AI**: Define ethical principles and constraints\n",
                "2. **Stakeholder Integration**: Incorporate diverse stakeholder perspectives\n",
                "3. **Constraint Evaluation**: Apply hard and soft ethical constraints\n",
                "4. **Multi-Objective Optimization**: Balance economic efficiency with ethical compliance\n",
                "5. **Bias Detection**: Identify and mitigate systemic biases\n",
                "6. **Compliance Monitoring**: Continuous audit and ethical performance tracking\n",
                "\n",
                "### What to look for in the results\n",
                "- Ethical constraint satisfaction rates\n",
                "- Stakeholder value alignment scores\n",
                "- Bias detection and mitigation effectiveness\n",
                "- Compliance monitoring outcomes\n",
                "- Multi-objective optimization trade-offs\n",
                "\n",
                "### Concrete example (from the source)\n",
                "TechFlow Industries implements ethical supplier selection:\n",
                "- 5 stakeholder groups (customers, employees, investors, suppliers, community)\n",
                "- 12 ethical constraints (hard and soft)\n",
                "- Constitutional AI with 7 core principles\n",
                "- Bias detection across 6 protected attributes\n",
                "- Real-time compliance monitoring dashboard\n",
                "\n",
                "### Visualization(s)\n",
                "- Stakeholder value distribution analysis\n",
                "- Ethical constraint satisfaction heatmap\n",
                "- Bias detection and mitigation timeline\n",
                "- Multi-objective Pareto frontier\n",
                "- Compliance monitoring dashboard\n",
                "\n",
                "### Why this Tier exists vs earlier Tiers\n",
                "This tier introduces ethical AI and value alignment that transcends pure optimization:\n",
                "- **Ethical constraints** vs purely economic optimization\n",
                "- **Multi-stakeholder value** vs single-objective decisions\n",
                "- **Constitutional AI** vs uncontrolled algorithmic decisions\n",
                "- **Bias mitigation** vs potentially biased historical data\n",
                "- **Continuous compliance** vs one-time ethical screening\n",
                "\n",
                "### Advantages vs Disadvantages\n",
                "**Advantages:**\n",
                "- Aligns decisions with organizational values and ethics\n",
                "- Addresses stakeholder concerns and social responsibility\n",
                "- Mitigates legal and reputational risks\n",
                "- Promotes long-term sustainable relationships\n",
                "- Builds trust with customers and stakeholders\n",
                "\n",
                "**Disadvantages:**\n",
                "- Increased complexity in decision making\n",
                "- Potential reduction in pure economic efficiency\n",
                "- Requires continuous monitoring and maintenance\n",
                "- May slow down decision processes\n",
                "- Complex stakeholder preference aggregation\n",
                "\n",
                "### When to use this Tier\n",
                "- **Publicly traded companies** with ESG requirements\n",
                "- **Government contractors** with compliance requirements\n",
                "- **Global supply chains** with diverse regulatory environments\n",
                "- **Consumer-facing brands** with reputation concerns\n",
                "- **Mission-driven organizations** with strong value systems"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import required libraries\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "from typing import Dict, List, Tuple, Any, Optional\n",
                "from dataclasses import dataclass\n",
                "import random\n",
                "import time\n",
                "from collections import defaultdict\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# Set plotting style\n",
                "plt.style.use('default')\n",
                "sns.set_palette(\"husl\")\n",
                "\n",
                "print(\"Libraries imported successfully for P88-Tier-8: Value-Aligned & Ethical Framework\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "@dataclass\n",
                "class EthicalConstraint:\n",
                "    \"\"\"Ethical constraint data structure\"\"\"\n",
                "    name: str\n",
                "    constraint_type: str  # 'hard' or 'soft'\n",
                "    threshold: float\n",
                "    weight: float\n",
                "    description: str\n",
                "    \n",
                "@dataclass\n",
                "class StakeholderGroup:\n",
                "    \"\"\"Stakeholder group data structure\"\"\"\n",
                "    name: str\n",
                "    priorities: Dict[str, float]\n",
                "    influence_weight: float\n",
                "    \n",
                "@dataclass\n",
                "class EthicalSupplierData:\n",
                "    \"\"\"Supplier data with ethical metrics\"\"\"\n",
                "    id: int\n",
                "    name: str\n",
                "    cost_performance: float\n",
                "    quality_score: float\n",
                "    delivery_reliability: float\n",
                "    ethical_metrics: Dict[str, float]\n",
                "    bias_indicators: Dict[str, float]"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Define ethical constraints\n",
                "ethical_constraints = [\n",
                "    EthicalConstraint(\"child_labor\", \"hard\", 0.0, 1000, \"Zero tolerance for child labor\"),\n",
                "    EthicalConstraint(\"living_wage\", \"soft\", 0.8, 50, \"Living wage compliance\"),\n",
                "    EthicalConstraint(\"safety_standards\", \"hard\", 0.9, 100, \"Workplace safety standards\"),\n",
                "    EthicalConstraint(\"environmental_impact\", \"soft\", 0.7, 25, \"Environmental impact score\"),\n",
                "    EthicalConstraint(\"gender_equality\", \"soft\", 0.8, 30, \"Gender equality in workforce\"),\n",
                "    EthicalConstraint(\"corruption_free\", \"hard\", 0.95, 200, \"Corruption-free operations\"),\n",
                "    EthicalConstraint(\"local_community_impact\", \"soft\", 0.6, 20, \"Positive local community impact\"),\n",
                "    EthicalConstraint(\"supply_chain_transparency\", \"soft\", 0.8, 15, \"Supply chain transparency\")\n",
                "]\n",
                "\n",
                "# Define stakeholder groups\n",
                "stakeholders = [\n",
                "    StakeholderGroup(\"Customers\", {\"quality\": 0.4, \"cost\": 0.3, \"ethics\": 0.3}, 0.25),\n",
                "    StakeholderGroup(\"Employees\", {\"ethics\": 0.5, \"safety\": 0.3, \"job_security\": 0.2}, 0.20),\n",
                "    StakeholderGroup(\"Investors\", {\"cost\": 0.5, \"risk\": 0.3, \"ethics\": 0.2}, 0.20),\n",
                "    StakeholderGroup(\"Suppliers\", {\"fairness\": 0.4, \"stability\": 0.4, \"ethics\": 0.2}, 0.15),\n",
                "    StakeholderGroup(\"Community\", {\"environment\": 0.4, \"local_impact\": 0.4, \"ethics\": 0.2}, 0.20)\n",
                "]\n",
                "\n",
                "print(f\"Ethical Framework initialized:\")\n",
                "print(f\"  Constraints: {len(ethical_constraints)} ({len([c for c in ethical_constraints if c.constraint_type == 'hard'])} hard)\")\n",
                "print(f\"  Stakeholder Groups: {len(stakeholders)}\")\n",
                "\n",
                "for constraint in ethical_constraints:\n",
                "    print(f\"    - {constraint.name}: {constraint.constraint_type} (threshold: {constraint.threshold:.1f})\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class ConstitutionalAI:\n",
                "    \"\"\"Constitutional AI system for ethical supplier selection\"\"\"\n",
                "    \n",
                "    def __init__(self, constraints: List[EthicalConstraint], \n",
                "                 stakeholders: List[StakeholderGroup]):\n",
                "        self.constraints = constraints\n",
                "        self.stakeholders = stakeholders\n",
                "        self constitutional_principles = [\n",
                "            \"Do no harm to stakeholders\",\n",
                "            \"Promote fairness and equality\",\n",
                "            \"Ensure transparency and accountability\",\n",
                "            \"Protect the environment\",\n",
                "            \"Uphold human rights\",\n",
                "            \"Maintain business integrity\",\n",
                "            \"Create sustainable value\"\n",
                "        ]\n",
                "        self.bias_detector = BiasDetectionSystem()\n",
                "        \n",
                "    def evaluate_supplier_ethics(self, supplier: EthicalSupplierData) -> Dict[str, Any]:\n",
                "        \"\"\"Evaluate supplier against ethical constraints\"\"\"\n",
                "        \n",
                "        evaluation = {\n",
                "            'supplier_name': supplier.name,\n",
                "            'ethical_score': 1.0,\n",
                "            'constraint_violations': [],\n",
                "            'constraint_compliance': {},\n",
                "            'bias_analysis': {},\n",
                "            'stakeholder_alignment': {}\n",
                "        }\n",
                "        \n",
                "        # Evaluate each constraint\n",
                "        for constraint in self.constraints:\n",
                "            value = supplier.ethical_metrics.get(constraint.name, 0.5)\n",
                "            \n",
                "            if constraint.constraint_type == 'hard':\n",
                "                if value < constraint.threshold:\n",
                "                    evaluation['constraint_violations'].append(constraint.name)\n",
                "                    evaluation['ethical_score'] = 0.0  # Hard constraint violation = fail\n",
                "                    evaluation['constraint_compliance'][constraint.name] = False\n",
                "                else:\n",
                "                    evaluation['constraint_compliance'][constraint.name] = True\n",
                "            else:  # soft constraint\n",
                "                if value < constraint.threshold:\n",
                "                    penalty = (constraint.threshold - value) * constraint.weight / 100\n",
                "                    evaluation['ethical_score'] -= penalty\n",
                "                    evaluation['constraint_compliance'][constraint.name] = False\n",
                "                else:\n",
                "                    evaluation['constraint_compliance'][constraint.name] = True\n",
                "        \n",
                "        # Bias analysis\n",
                "        evaluation['bias_analysis'] = self.bias_detector.analyze_bias(supplier.bias_indicators)\n",
                "        \n",
                "        # Stakeholder alignment\n",
                "        evaluation['stakeholder_alignment'] = self.calculate_stakeholder_alignment(supplier)\n",
                "        \n",
                "        return evaluation\n",
                "    \n",
                "    def calculate_stakeholder_alignment(self, supplier: EthicalSupplierData) -> Dict[str, float]:\n",
                "        \"\"\"Calculate alignment with stakeholder priorities\"\"\"\n",
                "        alignment = {}\n",
                "        \n",
                "        for stakeholder in self.stakeholders:\n",
                "            score = 0.0\n",
                "            \n",
                "            for priority, weight in stakeholder.priorities.items():\n",
                "                if priority == \"quality\":\n",
                "                    score += supplier.quality_score * weight\n",
                "                elif priority == \"cost\":\n",
                "                    score += supplier.cost_performance * weight\n",
                "                elif priority == \"ethics\":\n",
                "                    score += np.mean(list(supplier.ethical_metrics.values())) * weight\n",
                "                elif priority == \"safety\":\n",
                "                    score += supplier.ethical_metrics.get(\"safety_standards\", 0.5) * weight\n",
                "                elif priority == \"environment\":\n",
                "                    score += supplier.ethical_metrics.get(\"environmental_impact\", 0.5) * weight\n",
                "                elif priority == \"fairness\":\n",
                "                    score += supplier.ethical_metrics.get(\"gender_equality\", 0.5) * weight\n",
                "                # Add more priority mappings as needed\n",
                "            \n",
                "            alignment[stakeholder.name] = score\n",
                "        \n",
                "        return alignment\n",
                "    \n",
                "    def multi_objective_optimization(self, suppliers: List[EthicalSupplierData]) -> Dict[str, Any]:\n",
                "        \"\"\"Perform multi-objective optimization balancing ethics and economics\"\"\"\n",
                "        \n",
                "        results = []\n",
                "        \n",
                "        for supplier in suppliers:\n",
                "            ethics_eval = self.evaluate_supplier_ethics(supplier)\n",
                "            \n",
                "            # Calculate composite score\n",
                "            economic_score = (supplier.cost_performance + supplier.quality_score + \n",
                "                           supplier.delivery_reliability) / 3\n",
                "            \n",
                "            # Weight ethics and economics (ethics weighted more heavily)\n",
                "            ethics_weight = 0.6\n",
                "            economic_weight = 0.4\n",
                "            \n",
                "            composite_score = (ethics_eval['ethical_score'] * ethics_weight + \n",
                "                             economic_score * economic_weight)\n",
                "            \n",
                "            # Calculate stakeholder-weighted score\n",
                "            stakeholder_score = 0.0\n",
                "            for stakeholder_name, alignment in ethics_eval['stakeholder_alignment'].items():\n",
                "                stakeholder = next(s for s in self.stakeholders if s.name == stakeholder_name)\n",
                "                stakeholder_score += alignment * stakeholder.influence_weight\n",
                "            \n",
                "            results.append({\n",
                "                'supplier': supplier.name,\n",
                "                'ethical_score': ethics_eval['ethical_score'],\n",
                "                'economic_score': economic_score,\n",
                "                'composite_score': composite_score,\n",
                "                'stakeholder_score': stakeholder_score,\n",
                "                'violations': len(ethics_eval['constraint_violations']),\n",
                "                'bias_risk': ethics_eval['bias_analysis']['overall_risk']\n",
                "            })\n",
                "        \n",
                "        # Sort by composite score\n",
                "        results.sort(key=lambda x: x['composite_score'], reverse=True)\n",
                "        \n",
                "        return {\n",
                "            'ranked_suppliers': results,\n",
                "            'pareto_frontier': self._find_pareto_frontier(results)\n",
                "        }\n",
                "    \n",
                "    def _find_pareto_frontier(self, results: List[Dict]) -> List[Dict]:\n",
                "        \"\"\"Find Pareto frontier in ethics-economics trade-off\"\"\"\n",
                "        pareto = []\n",
                "        \n",
                "        for i, result in enumerate(results):\n",
                "            dominated = False\n",
                "            for j, other in enumerate(results):\n",
                "                if i != j:\n",
                "                    # Check if other dominates result\n",
                "                    if (other['ethical_score'] >= result['ethical_score'] and \n",
                "                        other['economic_score'] >= result['economic_score'] and \n",
                "                        (other['ethical_score'] > result['ethical_score'] or \n",
                "                         other['economic_score'] > result['economic_score'])):\n",
                "                        dominated = True\n",
                "                        break\n",
                "            \n",
                "            if not dominated:\n",
                "                pareto.append(result)\n",
                "        \n",
                "        return pareto"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class BiasDetectionSystem:\n",
                "    \"\"\"System for detecting and mitigating bias in supplier selection\"\"\"\n",
                "    \n",
                "    def __init__(self):\n",
                "        self.protected_attributes = [\n",
                "            'gender_bias', 'racial_bias', 'geographic_bias', \n",
                "            'size_bias', 'age_bias', 'cultural_bias'\n",
                "        ]\n",
                "        self.bias_threshold = 0.2\n",
                "        \n",
                "    def analyze_bias(self, bias_indicators: Dict[str, float]) -> Dict[str, Any]:\n",
                "        \"\"\"Analyze bias indicators and identify potential issues\"\"\"\n",
                "        \n",
                "        analysis = {\n",
                "            'detected_biases': [],\n",
                "            'bias_scores': {},\n",
                "            'overall_risk': 0.0,\n",
                "            'mitigation_needed': False\n",
                "        }\n",
                "        \n",
                "        max_bias = 0.0\n",
                "        \n",
                "        for attribute in self.protected_attributes:\n",
                "            bias_score = bias_indicators.get(attribute, 0.0)\n",
                "            analysis['bias_scores'][attribute] = bias_score\n",
                "            \n",
                "            if bias_score > self.bias_threshold:\n",
                "                analysis['detected_biases'].append(attribute)\n",
                "                analysis['mitigation_needed'] = True\n",
                "            \n",
                "            max_bias = max(max_bias, bias_score)\n",
                "        \n",
                "        analysis['overall_risk'] = max_bias\n",
                "        \n",
                "        return analysis\n",
                "    \n",
                "    def suggest_mitigation(self, bias_analysis: Dict[str, Any]) -> List[str]:\n",
                "        \"\"\"Suggest bias mitigation strategies\"\"\"\n",
                "        suggestions = []\n",
                "        \n",
                "        for bias in bias_analysis['detected_biases']:\n",
                "            if bias == 'gender_bias':\n",
                "                suggestions.append(\"Implement gender-blind evaluation criteria\")\n",
                "                suggestions.append(\"Set diversity targets for supplier portfolio\")\n",
                "            elif bias == 'geographic_bias':\n",
                "                suggestions.append(\"Expand supplier search to underrepresented regions\")\n",
                "                suggestions.append(\"Implement regional diversity requirements\")\n",
                "            elif bias == 'size_bias':\n",
                "                suggestions.append(\"Create evaluation categories for different company sizes\")\n",
                "                suggestions.append(\"Set minimum percentage for small suppliers\")\n",
                "            else:\n",
                "                suggestions.append(f\"Implement targeted bias mitigation for {bias}\")\n",
                "        \n",
                "        return suggestions"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Create sample suppliers with ethical metrics\n",
                "suppliers = [\n",
                "    EthicalSupplierData(\n",
                "        1, \"EthiCorp Global\", 0.85, 0.92, 0.88,\n",
                "        {\n",
                "            'child_labor': 0.0, 'living_wage': 0.95, 'safety_standards': 0.98,\n",
                "            'environmental_impact': 0.82, 'gender_equality': 0.88, 'corruption_free': 0.97,\n",
                "            'local_community_impact': 0.75, 'supply_chain_transparency': 0.90\n",
                "        },\n",
                "        {\n",
                "            'gender_bias': 0.05, 'racial_bias': 0.08, 'geographic_bias': 0.12,\n",
                "            'size_bias': 0.15, 'age_bias': 0.03, 'cultural_bias': 0.10\n",
                "        }\n",
                "    ),\n",
                "    EthicalSupplierData(\n",
                "        2, \"ValueTech Solutions\", 0.78, 0.85, 0.92,\n",
                "        {\n",
                "            'child_labor': 0.0, 'living_wage': 0.82, 'safety_standards': 0.91,\n",
                "            'environmental_impact': 0.71, 'gender_equality': 0.76, 'corruption_free': 0.89,\n",
                "            'local_community_impact': 0.68, 'supply_chain_transparency': 0.78\n",
                "        },\n",
                "        {\n",
                "            'gender_bias': 0.18, 'racial_bias': 0.12, 'geographic_bias': 0.08,\n",
                "            'size_bias': 0.22, 'age_bias': 0.05, 'cultural_bias': 0.15\n",
                "        }\n",
                "    ),\n",
                "    EthicalSupplierData(\n",
                "        3, \"FairTrade Partners\", 0.72, 0.88, 0.85,\n",
                "        {\n",
                "            'child_labor': 0.0, 'living_wage': 0.98, 'safety_standards': 0.94,\n",
                "            'environmental_impact': 0.91, 'gender_equality': 0.92, 'corruption_free': 0.96,\n",
                "            'local_community_impact': 0.88, 'supply_chain_transparency': 0.95\n",
                "        },\n",
                "        {\n",
                "            'gender_bias': 0.02, 'racial_bias': 0.05, 'geographic_bias': 0.25,\n",
                "            'size_bias': 0.08, 'age_bias': 0.03, 'cultural_bias': 0.12\n",
                "        }\n",
                "    ),\n",
                "    EthicalSupplierData(\n",
                "        4, \"CostFirst Manufacturing\", 0.92, 0.75, 0.90,\n",
                "        {\n",
                "            'child_labor': 0.05, 'living_wage': 0.65, 'safety_standards': 0.78,\n",
                "            'environmental_impact': 0.52, 'gender_equality': 0.68, 'corruption_free': 0.82,\n",
                "            'local_community_impact': 0.45, 'supply_chain_transparency': 0.71\n",
                "        },\n",
                "        {\n",
                "            'gender_bias': 0.28, 'racial_bias': 0.22, 'geographic_bias': 0.15,\n",
                "            'size_bias': 0.35, 'age_bias': 0.12, 'cultural_bias': 0.18\n",
                "        }\n",
                "    )\n",
                "]\n",
                "\n",
                "# Initialize the Constitutional AI system\n",
                "constitutional_ai = ConstitutionalAI(ethical_constraints, stakeholders)\n",
                "\n",
                "print(f\"Ethical Supplier Evaluation System initialized:\")\n",
                "print(f\"  Suppliers: {len(suppliers)}\")\n",
                "print(f\"  Constitutional Principles: {len(constitutional_ai.constitutional_principles)}\")\n",
                "print(f\"  Bias Detection Attributes: {len(constitutional_ai.bias_detector.protected_attributes)}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Evaluate all suppliers ethically\n",
                "ethical_evaluations = []\n",
                "\n",
                "for supplier in suppliers:\n",
                "    evaluation = constitutional_ai.evaluate_supplier_ethics(supplier)\n",
                "    ethical_evaluations.append(evaluation)\n",
                "    \n",
                "    print(f\"\\n=== {supplier.name} ===\")\n",
                "    print(f\"Ethical Score: {evaluation['ethical_score']:.3f}\")\n",
                "    print(f\"Constraint Violations: {len(evaluation['constraint_violations'])}\")\n",
                "    if evaluation['constraint_violations']:\n",
                "        print(f\"  Violations: {', '.join(evaluation['constraint_violations'])}\")\n",
                "    \n",
                "    print(f\"Bias Risk: {evaluation['bias_analysis']['overall_risk']:.3f}\")\n",
                "    if evaluation['bias_analysis']['detected_biases']:\n",
                "        print(f\"  Detected Biases: {', '.join(evaluation['bias_analysis']['detected_biases'])}\")\n",
                "    \n",
                "    print(f\"Stakeholder Alignment:\")\n",
                "    for stakeholder, score in evaluation['stakeholder_alignment'].items():\n",
                "        print(f\"  {stakeholder}: {score:.3f}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Perform multi-objective optimization\n",
                "optimization_results = constitutional_ai.multi_objective_optimization(suppliers)\n",
                "\n",
                "print(\"=== MULTI-OBJECTIVE OPTIMIZATION RESULTS ===\")\n",
                "print(f\"\\nRanked Suppliers (Ethics + Economics):\")\n",
                "for i, result in enumerate(optimization_results['ranked_suppliers'], 1):\n",
                "    print(f\"{i}. {result['supplier']}\")\n",
                "    print(f\"   Composite Score: {result['composite_score']:.3f}\")\n",
                "    print(f\"   Ethical Score: {result['ethical_score']:.3f}\")\n",
                "    print(f\"   Economic Score: {result['economic_score']:.3f}\")\n",
                "    print(f\"   Stakeholder Score: {result['stakeholder_score']:.3f}\")\n",
                "    print(f\"   Violations: {result['violations']}, Bias Risk: {result['bias_risk']:.3f}\")\n",
                "    print()\n",
                "\n",
                "print(f\"Pareto Frontier (Non-dominated solutions):\")\n",
                "for result in optimization_results['pareto_frontier']:\n",
                "    print(f\"  - {result['supplier']}: Ethics={result['ethical_score']:.3f}, Economics={result['economic_score']:.3f}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def visualize_ethical_framework(evaluations: List[Dict], \n",
                "                               optimization_results: Dict): \n",
                "    \"\"\"Create comprehensive visualization of ethical framework\"\"\"\n",
                "    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(16, 12))\n",
                "    \n",
                "    # 1. Ethical Constraint Compliance Heatmap\n",
                "    constraint_names = [c.name for c in ethical_constraints]\n",
                "    supplier_names = [eval['supplier_name'] for eval in evaluations]\n",
                "    \n",
                "    compliance_matrix = []\n",
                "    for eval in evaluations:\n",
                "        compliance_row = []\n",
                "        for constraint in constraint_names:\n",
                "            compliance_row.append(1.0 if eval['constraint_compliance'].get(constraint, False) else 0.0)\n",
                "        compliance_matrix.append(compliance_row)\n",
                "    \n",
                "    sns.heatmap(compliance_matrix, xticklabels=constraint_names, \n",
                "               yticklabels=supplier_names, annot=True, cmap='RdYlGn', \n",
                "               ax=ax1, cbar_kws={'label': 'Compliance'})\n",
                "    ax1.set_title('Ethical Constraint Compliance', fontweight='bold')\n",
                "    ax1.set_xlabel('Constraints')\n",
                "    ax1.set_ylabel('Suppliers')\n",
                "    \n",
                "    # 2. Stakeholder Alignment Radar Chart\n",
                "    angles = np.linspace(0, 2 * np.pi, len(stakeholders), endpoint=False).tolist()\n",
                "    angles += angles[:1]  # Complete the circle\n",
                "    \n",
                "    for eval in evaluations[:3]:  # Plot top 3 suppliers\n",
                "        values = [eval['stakeholder_alignment'][s.name] for s in stakeholders]\n",
                "        values += values[:1]  # Complete the circle\n",
                "        ax2.plot(angles, values, 'o-', linewidth=2, label=eval['supplier_name'])\n",
                "        ax2.fill(angles, values, alpha=0.25)\n",
                "    \n",
                "    ax2.set_xticks(angles[:-1])\n",
                "    ax2.set_xticklabels([s.name for s in stakeholders])\n",
                "    ax2.set_ylim(0, 1)\n",
                "    ax2.set_title('Stakeholder Alignment Analysis', fontweight='bold')\n",
                "    ax2.legend()\n",
                "    \n",
                "    # 3. Ethics vs Economics Scatter Plot\n",
                "    ranked_results = optimization_results['ranked_suppliers']\n",
                "    ethics_scores = [r['ethical_score'] for r in ranked_results]\n",
                "    economic_scores = [r['economic_score'] for r in ranked_results]\n",
                "    supplier_names = [r['supplier'] for r in ranked_results]\n",
                "    \n",
                "    scatter = ax3.scatter(economic_scores, ethics_scores, s=100, alpha=0.7)\n",
                "    ax3.set_xlabel('Economic Score')\n",
                "    ax3.set_ylabel('Ethical Score')\n",
                "    ax3.set_title('Ethics vs Economics Trade-off', fontweight='bold')\n",
                "    ax3.grid(True, alpha=0.3)\n",
                "    ax3.set_xlim(0.6, 1.0)\n",
                "    ax3.set_ylim(0, 1.0)\n",
                "    \n",
                "    # Add supplier labels\n",
                "    for i, name in enumerate(supplier_names):\n",
                "        ax3.annotate(name, (economic_scores[i], ethics_scores[i]), \n",
                "                    xytext=(5, 5), textcoords='offset points', fontsize=9)\n",
                "    \n",
                "    # Highlight Pareto frontier\n",
                "    pareto_results = optimization_results['pareto_frontier']\n",
                "    pareto_ethics = [r['ethical_score'] for r in pareto_results]\n",
                "    pareto_economics = [r['economic_score'] for r in pareto_results]\n",
                "    ax3.scatter(pareto_economics, pareto_ethics, s=150, alpha=0.8, \n",
                "               marker='*', edgecolor='red', linewidth=2, label='Pareto Frontier')\n",
                "    ax3.legend()\n",
                "    \n",
                "    # 4. Bias Risk Analysis\n",
                "    bias_categories = list(constitutional_ai.bias_detector.protected_attributes)\n",
                "    bias_data = []\n",
                "    \n",
                "    for eval in evaluations:\n",
                "        bias_scores = [eval['bias_analysis']['bias_scores'].get(cat, 0) for cat in bias_categories]\n",
                "        bias_data.append(bias_scores)\n",
                "    \n",
                "    bias_array = np.array(bias_data).T\n",
                "    x = np.arange(len(bias_categories))\n",
                "    width = 0.2\n",
                "    \n",
                "    for i, supplier_name in enumerate(supplier_names):\n",
                "        ax4.bar(x + i * width, bias_array[:, i], width, label=supplier_name, alpha=0.8)\n",
                "    \n",
                "    ax4.set_xlabel('Bias Categories')\n",
                "    ax4.set_ylabel('Bias Score')\n",
                "    ax4.set_title('Bias Risk Analysis by Supplier', fontweight='bold')\n",
                "    ax4.set_xticks(x + width * 1.5)\n",
                "    ax4.set_xticklabels([cat.replace('_', ' ').title() for cat in bias_categories], \n",
                "                      rotation=45, ha='right')\n",
                "    ax4.legend()\n",
                "    ax4.grid(True, alpha=0.3, axis='y')\n",
                "    ax4.axhline(y=constitutional_ai.bias_detector.bias_threshold, \n",
                "               color='red', linestyle='--', alpha=0.7, label='Threshold')\n",
                "    \n",
                "    plt.tight_layout()\n",
                "    plt.savefig('p88_tier8_ethical_framework.png', dpi=300, bbox_inches='tight')\n",
                "    plt.show()\n",
                "    \n",
                "    return fig\n",
                "\n",
                "# Visualize the ethical framework\n",
                "fig = visualize_ethical_framework(ethical_evaluations, optimization_results)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def demonstrate_bias_mitigation():\n",
                "    \"\"\"Demonstrate bias detection and mitigation strategies\"\"\"\n",
                "    \n",
                "    print(\"=== BIAS MITIGATION DEMONSTRATION ===\")\n",
                "    \n",
                "    # Find suppliers with bias issues\n",
                "    biased_suppliers = []\n",
                "    for i, supplier in enumerate(suppliers):\n",
                "        bias_analysis = ethical_evaluations[i]['bias_analysis']\n",
                "        if bias_analysis['mitigation_needed']:\n",
                "            biased_suppliers.append((supplier.name, bias_analysis))\n",
                "    \n",
                "    if biased_suppliers:\n",
                "        print(f\"\\nSuppliers requiring bias mitigation:\")\n",
                "        for supplier_name, bias_analysis in biased_suppliers:\n",
                "            print(f\"\\n{supplier_name}:\")\n",
                "            print(f\"  Overall Risk: {bias_analysis['overall_risk']:.3f}\")\n",
                "            print(f\"  Detected Biases: {', '.join(bias_analysis['detected_biases'])}\")\n",
                "            \n",
                "            # Get mitigation suggestions\n",
                "            suggestions = constitutional_ai.bias_detector.suggest_mitigation(bias_analysis)\n",
                "            print(f\"  Mitigation Strategies:\")\n",
                "            for j, suggestion in enumerate(suggestions, 1):\n",
                "                print(f\"    {j}. {suggestion}\")\n",
                "    else:\n",
                "        print(\"No significant bias detected in current suppliers.\")\n",
                "    \n",
                "    # Simulate bias reduction after mitigation\n",
                "    print(f\"\\n=== SIMULATED BIAS REDUCTION ===\")\n",
                "    for supplier_name, bias_analysis in biased_suppliers[:1]:  # Demonstrate with first biased supplier\n",
                "        print(f\"\\nBefore mitigation for {supplier_name}:\")\n",
                "        for bias, score in bias_analysis['bias_scores'].items():\n",
                "            if bias in bias_analysis['detected_biases']:\n",
                "                print(f\"  {bias}: {score:.3f}\")\n",
                "        \n",
                "        # Simulate 50% reduction in detected biases\n",
                "        print(f\"\\nAfter mitigation (simulated 50% reduction):\")\n",
                "        for bias, score in bias_analysis['bias_scores'].items():\n",
                "            if bias in bias_analysis['detected_biases']:\n",
                "                reduced_score = score * 0.5\n",
                "                status = \"✓ Below threshold\" if reduced_score < constitutional_ai.bias_detector.bias_threshold else \"⚠ Still above threshold\"\n",
                "                print(f\"  {bias}: {reduced_score:.3f} {status}\")\n",
                "\n",
                "# Demonstrate bias mitigation\n",
                "demonstrate_bias_mitigation()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def compliance_monitoring_simulation():\n",
                "    \"\"\"Simulate continuous compliance monitoring\"\"\"\n",
                "    \n",
                "    print(\"=== COMPLIANCE MONITORING SIMULATION ===\")\n",
                "    \n",
                "    # Simulate monthly compliance checks over 6 months\n",
                "    months = ['Month 1', 'Month 2', 'Month 3', 'Month 4', 'Month 5', 'Month 6']\n",
                "    compliance_trends = {}\n",
                "    \n",
                "    for supplier in suppliers:\n",
                "        compliance_trends[supplier.name] = []\n",
                "        base_ethical_score = np.mean([e['ethical_score'] for e in ethical_evaluations \n",
                "                               if e['supplier_name'] == supplier.name])\n",
                "        \n",
                "        for i, month in enumerate(months):\n",
                "            # Simulate compliance variation (some improvement over time)\n",
                "            improvement = i * 0.02  # 2% improvement per month\n",
                "            random_variation = np.random.normal(0, 0.01)  # Small random variation\n",
                "            monthly_score = min(1.0, base_ethical_score + improvement + random_variation)\n",
                "            compliance_trends[supplier.name].append(monthly_score)\n",
                "    \n",
                "    # Create compliance trend visualization\n",
                "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))\n",
                "    \n",
                "    # Plot 1: Compliance trends over time\n",
                "    for supplier_name, scores in compliance_trends.items():\n",
                "        ax1.plot(months, scores, 'o-', linewidth=2, label=supplier_name, markersize=6)\n",
                "    \n",
                "    ax1.set_xlabel('Time Period')\n",
                "    ax1.set_ylabel('Compliance Score')\n",
                "    ax1.set_title('Compliance Monitoring Trends', fontweight='bold')\n",
                "    ax1.grid(True, alpha=0.3)\n",
                "    ax1.legend()\n",
                "    ax1.set_ylim(0.6, 1.0)\n",
                "    \n",
                "    # Plot 2: Compliance distribution at final month\n",
                "    final_scores = [scores[-1] for scores in compliance_trends.values()]\n",
                "    supplier_names_final = list(compliance_trends.keys())\n",
                "    \n",
                "    bars = ax2.bar(supplier_names_final, final_scores, \n",
                "                   color=['green' if score >= 0.8 else 'orange' if score >= 0.7 else 'red' \n",
                "                          for score in final_scores], alpha=0.7)\n",
                "    \n",
                "    ax2.set_ylabel('Final Compliance Score')\n",
                "    ax2.set_title('Final Compliance Status', fontweight='bold')\n",
                "    ax2.set_ylim(0.6, 1.0)\n",
                "    ax2.tick_params(axis='x', rotation=45)\n",
                "    ax2.grid(True, alpha=0.3, axis='y')\n",
                "    \n",
                "    # Add threshold line\n",
                "    ax2.axhline(y=0.8, color='green', linestyle='--', alpha=0.7, label='Target (80%)')\n",
                "    ax2.axhline(y=0.7, color='orange', linestyle='--', alpha=0.7, label='Minimum (70%)')\n",
                "    ax2.legend()\n",
                "    \n",
                "    # Add value labels on bars\n",
                "    for bar, score in zip(bars, final_scores):\n",
                "        ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,\n",
                "                f'{score:.3f}', ha='center', va='bottom', fontweight='bold')\n",
                "    \n",
                "    plt.tight_layout()\n",
                "    plt.savefig('p88_tier8_compliance_monitoring.png', dpi=300, bbox_inches='tight')\n",
                "    plt.show()\n",
                "    \n",
                "    # Print summary statistics\n",
                "    print(f\"\\nCompliance Summary (Month 6):\")\n",
                "    for supplier_name, scores in compliance_trends.items():\n",
                "        initial_score = scores[0]\n",
                "        final_score = scores[-1]\n",
                "        improvement = final_score - initial_score\n",
                "        status = \"✓ Compliant\" if final_score >= 0.8 else \"⚠ Needs Improvement\" if final_score >= 0.7 else \"✗ Non-Compliant\"\n",
                "        print(f\"  {supplier_name}: {final_score:.3f} ({improvement:+.3f}) {status}\")\n",
                "    \n",
                "    return fig\n",
                "\n",
                "# Run compliance monitoring simulation\n",
                "fig = compliance_monitoring_simulation()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Summary and Conclusions\n",
                "\n",
                "### Key Findings from Value-Aligned & Ethical Framework:\n",
                "\n",
                "1. **Ethical Constraint Integration**: Hard constraints (zero tolerance) effectively eliminate unacceptable suppliers, while soft constraints allow for balanced trade-offs.\n",
                "\n",
                "2. **Multi-Stakeholder Value**: Different stakeholder groups have competing priorities that require careful balancing in supplier selection decisions.\n",
                "\n",
                "3. **Bias Detection Effectiveness**: Systematic bias analysis identifies potential discrimination across multiple protected attributes.\n",
                "\n",
                "4. **Pareto Optimization**: Multi-objective optimization reveals the trade-offs between ethical performance and economic efficiency.\n",
                "\n",
                "5. **Continuous Monitoring**: Compliance tracking demonstrates improvement over time with proper feedback mechanisms.\n",
                "\n",
                "### Constitutional AI Advantages:\n",
                "\n",
                "- **Value Alignment**: Decisions consistently align with organizational values and ethical principles\n",
                "- **Stakeholder Representation**: Multiple stakeholder perspectives are systematically incorporated\n",
                "- **Bias Mitigation**: Proactive identification and correction of systemic biases\n",
                "- **Compliance Assurance**: Continuous monitoring ensures ongoing ethical performance\n",
                "- **Transparency**: Explainable decisions build trust and accountability\n",
                "\n",
                "### Implementation Considerations:\n",
                "\n",
                "- **Complexity Management**: Ethical frameworks add significant complexity to decision processes\n",
                "- **Performance Trade-offs**: Ethical constraints may reduce pure economic efficiency\n",
                "- **Data Requirements**: Comprehensive ethical and bias data is essential for effective operation\n",
                "- **Stakeholder Engagement**: Ongoing dialogue with stakeholders is required for alignment\n",
                "- **Monitoring Costs**: Continuous compliance monitoring requires resources and commitment\n",
                "\n",
                "### Business Value:\n",
                "\n",
                "The Value-Aligned & Ethical Framework provides substantial business value:\n",
                "- **Risk Mitigation**: Reduces legal, reputational, and regulatory risks\n",
                "- **Brand Enhancement**: Builds trust with customers and stakeholders\n",
                "- **Talent Attraction**: Aligns with employee values and ESG expectations\n",
                "- **Market Access**: Meets growing ESG requirements from customers and investors\n",
                "- **Long-term Sustainability**: Creates resilient and responsible supply chains\n",
                "\n",
                "### Future Evolution:\n",
                "\n",
                "The ethical framework represents the future of responsible AI in supply chain management:\n",
                "- **Adaptive Ethics**: Systems that learn and evolve ethical standards over time\n",
                "- **Global Standards**: Harmonization with international ethical frameworks\n",
                "- **Real-time Ethics**: Instant ethical compliance verification and decision support\n",
                "- **Stakeholder Democracy**: Direct stakeholder participation in AI governance\n",
                "- **Ethical AI Ecosystem**: Industry-wide ethical AI standards and certification\n",
                "\n",
                "This approach demonstrates how AI systems can be designed to align with human values while maintaining business effectiveness, setting a new standard for ethical supply chain management."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "Python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the fixed notebook
with open('P88-Tier-8-FIXED.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print("P88-Tier-8-FIXED.ipynb created successfully with proper JSON structure")
